var allMusic =[
    {   song_name:"被你遺忘的森林",
        singer:"原子邦妮",
        img:"music01",
        src:"music01" },
    {   song_name:"在這座城市遺失了你",
        singer:"告五人",
        img:"music02",
        src:"music02" },
    {   song_name:"暗流",
        singer:"拍謝少年 Sorry Youth",
        img:"music03",
        src:"music03" },
    {   song_name:"長途夜車",
        singer:"滅火器 Fire EX.",
        img:"music04",
        src:"music04" },
    {   song_name:"街仔路雨落袂停",
        singer:"鄭宜農 feat 陳嫺靜",
        img:"music05",
        src:"music05" },
        {   song_name:"後照鏡",
        singer:"怕胖團",
        img:"music06",
        src:"music06" },
        {   song_name:"遠行",
        singer:"Yellow 黃宣",
        img:"music07",
        src:"music07" },
        {   song_name:"藍色的你",
        singer:"宇宙人",
        img:"music08",
        src:"music08" },
        {   song_name:"在這個年代，找不到浪漫",
        singer:"溫室雜草",
        img:"music09",
        src:"music09" },
        {   song_name:"終究還是因為愛",
        singer:"THASH",
        img:"music10",
        src:"music10" },
        {   song_name:"對不起我做不到答應了你的事",
        singer:"康士坦的變化球",
        img:"music11",
        src:"music11" },
        {   song_name:"夜走",
        singer:"打倒三明治",
        img:"music12",
        src:"music12" },
];
var allLyrics = [
    {
        lyrics_title: "被你遺忘的森林",
        lyrics_text: "作詞 : 查查<br>作曲 : 查查、Nu<br><br>當冷冷的風 吹過我的 耳朵<br>我不管 任由他 冰凍<br>當過去的你 透過回憶 觸碰<br>Where we are<br>只剩下 沉默<br><br>為何 我還在這裡<br>被你 遺忘的森林<br>零度的空氣<br>凍結離開的勇氣<br>沒有誰 能夠代替<br>到現在 我還是想著你<br><br>為何 我還在這裡<br>徘徊 在你的過去<br>往事如夢境<br>佔據了夜的美麗<br>翻越寂寞的山嶺<br>每一天 我還是想著你<br><br>當黑色的雲 流浪繾綣 枝頭<br>光與虹 剩下我 補捉<br>當現在的你 關上回憶 塵封<br>我掉落 時間的 荒漠<br><br>為何 我還在這裡<br>被你 遺忘的森林<br>零度的空氣<br>凍結離開的勇氣<br>沒有誰 能夠代替<br>到現在 我還是想著你<br><br>為何 我還在這裡<br>徘徊 在你的過去<br>往事如夢境<br>佔據了夜的美麗<br>翻越寂寞的山嶺<br>每一天 我還是想著你<br><br>為何 我還在這裡<br>被你 遺忘的森林<br>零度的空氣<br>凍結離開的勇氣<br>沒有誰 能夠代替<br>到現在 我還是想著你<br><br>為何 我還在這裡<br>徘徊 在你的過去<br>往事如夢境<br>佔據了夜的美麗<br>翻越寂寞的山嶺<br>每一天 我還是想著你",
    },
    {
        lyrics_title: "在這座城市遺失了你",
        lyrics_text: "作詞 : 潘雲安<br>作曲 : 潘雲安<br><br>三番故里　窗外雨滴打破細碎的玻璃<br>與你相遇　是在一個單純美好的世界<br>而在變質那天　你淚流誇張情節<br>足以向全世界討回　你付出的一切<br><br>你的故事　存在一個需要密碼的盒子<br>紀念時刻　打開卻會冒出一陣陣白煙<br>像是警告自己　不能屈服嚮往從前<br>天變地變　我們的愛也變<br><br>而我　在這座城市　遺失了你<br>順便遺失了自己<br>以為荒唐到底　會有捷徑<br><br>而我　在這座城市　失去了你<br>輸給慾望高漲的自己<br>不是你　過分的感情<br><br>而我愛你　而愛無法　撐起<br>想擁有的　想擁抱的<br>以為能通向領悟的結局<br><br>你的故事　存在一個需要密碼的盒子<br>紀念時刻　打開卻會冒出一陣陣白煙<br>像是警告自己　不能屈服嚮往從前<br>天變地變　我們的愛也變<br><br>而我　在這座城市　遺失了你<br>順便遺失了自己<br>以為荒唐到底　會有捷徑<br><br>而我　在這座城市　失去了你<br>輸給慾望高漲的自己<br>不是你　過分的感情<br><br>而我愛你　而愛無法　撐起<br>想擁有的　想擁抱的<br>以為能通向領悟的結局",
    },
    {
        lyrics_title: "暗流",
        lyrics_text: "作詞 : 拍謝少年<br>作曲 : 拍謝少年<br><br>是傷心的滋味啊 想著過去的風景 猶原囥佇我心肝內 袂當袂記<br>是孤單的感覺啊 夢中看見你的臉 目屎掰袂離 無暝無日<br>欲安怎來講出喙 欲安怎來講出心內話 彼个懵懂的少年家 啊～<br>著放予去 著放袂記啊 人生<br><br>以前的咱 是無共現實看佇眼內<br>這馬的我 是勤儉拍拚為著未來<br>故鄉的風 是日日夜夜吹著阮心肝啊 佇遮啊<br><br>夢醒的歌聲啊 佇我心內唱啊<br>平凡的人 頂真的生活 是歌啊<br><br>這幾年 行入仝款的社會 賺著滿腹的怨慼 欲按怎對你來解釋<br>這幾年 行入仝款的社會 賺著滿腹的怨慼 欲按怎對你來解釋<br>聽 咱的歌聲 共阮的故事 唱予你聽<br>聽 咱的歌聲 共阮的故事 唱予你聽",
    },
    {
        lyrics_title: "長途夜車",
        lyrics_text: "作詞 : 楊大正 Sam Yang<br>作曲 : 楊大正 Sam Yang<br>編曲 : 滅火器 Fire EX.、鄭宇辰 ORio Cheng<br><br>時間是三點半<br>南下的長途夜車<br>路燈的光線<br>伴心事邊想邊走<br>說不出嘴的思念<br>寫不入未完的歌<br>人生是高速公路<br>我是趕路的車<br><br>想不起來那時侯怎麼離開<br>漂浪的生活漸漸習慣<br>迷糊經過這麼多年<br>認識到很多道理<br>卻找無一條路回去<br><br>看不到出口在哪裡<br>我漸漸失去自己<br>在競爭的花花世界<br>轉彎繞角是姑不而將<br><br>看不到出口在哪裡<br>也不知道該對兜去<br>我只是暫時失去方向<br>我一定會找到<br>回去的路<br><br>港邊的路 陣陣海風<br>吹入我的夢中<br>是當初 離開那個下午<br><br>走你的路 走你的路<br>你對我說<br>但是你要將回來的路 放在心中<br>我等你成功<br><br>時間是六點半<br>到站的長途夜車<br>下車的現在<br>我是回來的人",
    },
    {
        lyrics_title: "街仔路雨落袂停",
        lyrics_text: "作詞 : 鄭宜農 Enno Cheng/ 陳嫺靜 Hsien Ching<br>作曲 : 鄭宜農 Enno Cheng/ 陳嫺靜 Hsien Ching<br>編曲 : 何俊葦 Chun Ho、 王昱辰 Yuchain Wang<br><br>又是孤身的烏暗暝<br>人去樓空 心事茫茫<br>街仔路雨落袂停<br>你敢佇遐 思慕的人<br><br>一擺閣一擺 阮鬥陣唱悲傷的歌<br>你真正沒聽著我歌聲內的寄望？<br>往事親像海湧共阮淹甲毋知人<br>我毋甘願又踮佇遮<br>你敢欲做伙行？<br><br>又是孤身的烏暗暝<br>人去樓空 心事茫茫<br>街仔路雨落袂停<br>你敢佇遐 思慕的人<br><br>吹吹等甲風來吹<br>天頂的星攏歕落地<br>城市的燈火吹袂飛<br>茫茫大雨內底<br><br>吹吹等甲風來吹<br>天頂的星攏歕落地<br>城市的燈火吹袂飛<br><br><br>茫茫大雨內底 駛過你的巷子口<br>窗仔外人咧走 水咧流<br>親像做眠夢 有人對我大聲喝<br>哎喲 哎喲<br>聽著落雨聲就想著你<br>日頭出來前欲走對佗位去<br>坐佇車內嘛會淋著雨<br>我的火車走袂停<br><br>毋是無要緊 你是一擺兩擺三擺轉去就袂記得閣走<br>毋是無想你 是一擺兩擺三擺 我嘛佇給人等待<br><br>一擺又一擺 阮鬥陣唱悲傷的歌<br>你真正沒聽著我歌聲內的寄望？<br>往事親像海湧共阮淹甲毋知人<br>我毋甘願又踮佇遮<br>你敢欲做伙行？<br><br>街仔路雨落袂停<br>街仔路雨落袂停<br>街仔路雨落袂停",
    },
    {
        lyrics_title: "後照鏡",
        lyrics_text: "作詞 : 閃亮(謝侃均 Hsieh Kan-Chun)<br>作曲 : 閃亮(謝侃均 Hsieh Kan-Chun) 、 Weeman (謝孔均 Hsieh Kung- Chun)<br>編曲 : 怕胖團PAPUN BAND<br><br>今天 你穿了最愛的洋裝<br>還在我的耳邊五音不全 大聲歌唱<br>今天 你化了模糊的眼妝<br>請你躺在我的肩膀 我們不用說話<br><br>就抱緊我<br><br>今天 你吵著要我許願望<br>只希望明天的我們跟今天 都一樣<br><br>我想我不夠聰明<br>不應該再想起你<br>忘不了的回憶<br>總是讓我遇見你<br><br>我想我不夠聰明<br>以為他更適合你<br>不再能擁抱你<br>故事有什麼意義 沒有你<br><br>原來直到失去你 才知道我多愛你<br>我才能擁抱你 我才能擁抱你<br><br>不哭不哭 眼淚是珍珠<br>你會很幸福<br>不哭不哭 眼淚是珍珠<br>你會很幸福",
    },
    {
        lyrics_title: "遠行",
        lyrics_text: "作詞 : YELLOW黃宣<br>作曲 : YELLOW黃宣<br><br>我在一艘船<br>等待一個人揚起了帆<br>何時能靠岸<br>把遺憾留在一片沙灘<br><br>海很藍<br>我在你聽不見的距離吶喊<br>當我回頭看<br>太陽已漸入海岸<br><br>說是忘了 也有一點習慣<br>卻一直在腦海打轉<br>我沒把握<br>跟你說再見<br><br>我在一艘船<br>只有一個人揚起了帆<br>所以我繼續<br>順風的方向遠行",
    },
    {
        lyrics_title: "藍色的你",
        lyrics_text: "作詞 : 方奎棠 Cosmos Q、林忠諭 Cosmos J<br>作曲 : 林忠諭 Cosmos J<br>編曲 : 宇宙人、唐承運<br><br>Ups and downs and ups in my life<br>It comes and goes in waves that go by<br><br>我睡了整個夏天<br>它偷走我的時間觀念<br>藍色夢裡懶得閉上雙眼<br>難得出現是你藍色的臉<br><br>躺在你懷裡沈澱<br>看月光在你身體畫一條線<br>聽聽你輕輕呼吸悄悄入眠<br><br>裙擺上白色滾邊<br>沙灘上寫下諾言<br>穿過鵝卵石的隙間<br>告訴我你收信了沒<br><br>我有一點累 累得無法對你說再見<br>也許只是裝作無所謂<br>也許只是害怕潮退之後要離別<br><br><br>Ups and downs and ups in my life<br>It comes and goes in waves that go by<br><br>漂浮在混濁的夜<br>一百年不毀壞的眷戀<br>纏繞著我的身體乾擾知覺<br>我在暗潮活著在南島擱淺<br><br>躺在你懷裡沈澱<br>看月光在視線慢慢熄滅<br>聽聽你輕輕呼吸悄悄入眠<br><br>裙擺上白色滾邊<br>唱著古老的寓言<br>穿過鵝卵石的隙間<br>告訴我你聽見了沒<br><br>我有一點累 累得無法對你說再見<br>也許只是裝作無所謂<br>也許只是害怕潮退之後要離別<br><br>我有一點累 累得無法對你說再見<br>也許只是裝作無所謂<br>也許只是害怕潮退之後要離別<br><br>藍色的夢裡有藍色的臉藍色的你",
    },
    {
        lyrics_title: "在這個年代，找不到浪漫",
        lyrics_text: "作詞 : 劉偉頡<br>作曲 : 劉偉頡<br>編曲 : Easy Weeds 溫室雜草<br><br>我經過ㄧ家古著店<br>聊著底片<br>穿著ㄧ雙老爹鞋<br>抽著紙菸<br>跟著朋友聊著唱片<br>最喜歡王菲<br>因為妳快樂所以我快樂<br>在這個年代<br>找不到浪漫<br>子彈和逃難<br>都與我無關<br>在這個年代<br>我們不浪漫<br>我們的浪漫<br>都只是糜爛<br>或許生活就是逃難<br>時間是子彈<br>珍惜昨天勝過明天<br>才能快樂點<br>跟著朋友聊著唱片<br>最喜歡王菲<br>因為妳快樂所以我快樂<br>在這個年代<br>找不到浪漫<br>子彈和逃難<br>都與我無關<br>在這個年代<br>我們不浪漫<br>因為妳快樂所以我快樂<br>在這個年代<br>找不到浪漫<br>子彈和逃難<br>都與我無關<br>在這個年代<br>我們不浪漫<br>因為妳快樂所以我快樂",
    },
    {
        lyrics_title: "終究還是因為愛",
        lyrics_text: "作詞 : 阿夜<br>作曲 : 阿夜<br><br>感謝你曾經給我留下的傷<br>讓我有比從前要強悍的心臟<br>感謝在背後支撐住的力量<br>讓每次暴風雨來臨時還能擁有信仰<br><br>是什麼讓我們可以相遇<br>為什麼讓我們碎得支離<br>回頭看所有安排好的命運<br>才認識了註定<br><br>是你成為我的盔甲<br>抵抗所有千軍萬馬<br>是你讓我懂得原諒<br>放下過去凝視遠方<br>不掙扎不抵抗 接受失去擁抱徬徨<br>到最後 一直在尋找的答案<br>原來都是因為愛<br><br>再美的風景 如果沒有抬頭看<br>怎麼知道自己不用深陷在黑暗<br>Think about your love ones<br>Remember they're always around<br>找到你內在裡的答案就是解藥<br><br>是什麼讓我們可以相遇<br>為什麼讓我們碎得支離<br>回頭看所有安排好的命運<br>才認識了註定<br><br>是你成為我的盔甲<br>抵抗所有千軍萬馬<br>是你讓我懂得原諒<br>放下過去凝視遠方<br>不掙扎不抵抗 接受失去擁抱徬徨<br>到最後 一直在尋找的答案<br>原來都是因為愛<br><br>You make me wanna stay forever<br>Endless nights go on and on<br>Let's dive into this dream together<br>Just feel the vibe all around<br>I've been searching for the answer<br>Aimlessly looking around<br>In this moment nothing matters<br>And the answer is love<br><br>是你成為我的盔甲<br>抵抗所有千軍萬馬<br>是你讓我懂得原諒<br>放下過去凝視遠方<br>Just give in this feeling<br>And let it wash over your skin<br>到最後 一直在尋找的答案<br>終究還是因為愛<br>終究還是因為愛",
    },
    {
        lyrics_title: "對不起我做不到答應了你的事",
        lyrics_text: "作詞 : ARNY Wu<br>作曲 : 康士坦的變化球<br>編曲 : 康士坦的變化球<br><br>如果 承 諾<br>是囚 禁 善良 的鎖<br>那 麼 自私的人<br>一定過得 很快 樂吧？<br>或許 我 們<br>對未來 的想像 不一樣<br>那麼 強求來的<br>會真的 快 樂嗎？<br><br>說不清的難言之隱也得到了一刻安寧<br>可是太多不經意的謊言，一步又一步做了最爛的決定<br><br>對不起<br>我做不到答應了你的事<br>這讓你懷疑自己<br>變成了一廂情願的傻子<br>對不起<br>我做不到答應了你的事<br>這讓我痛恨我自己<br>變成了一個說謊的騙子",
    },
    {
        lyrics_title: "夜走",
        lyrics_text: "作詞 : 王欣茹<br>作曲 : 王欣茹<br><br>只是想和你並肩向前走 卻濺起水花<br>本以為雨滴只是輕輕的 落在他的肩上<br>風雨過了一季 還會再來 這是無法避免的啊<br>我們只能將自己 包覆得更緊<br><br>困在了沒有溫度的世界裡 天空也不知何時會亮<br>走在沒有人群的海岸邊 獨自說著沒人聽懂的道理<br><br>我在你的手心畫一個圈 走啊走的走不停啊<br>放開瞬間 我能了解 走得太遠回不去了<br>用那些累積 想說的話 推擠漸層的高牆<br>誰能夠讓 大雨落在 乾枯了你我的範圍",
    }
];